# Generated by Django 4.2.18 on 2026-03-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Кратко описание'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/previews/', verbose_name='Снимка за галерията (JPG/PNG)'),
        ),
    ]
